CREATE TABLE Person
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     varchar(100) NOT NULL UNIQUE,
    year_of_birth int          NOT NULL
);

CREATE TABLE Car
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_title     varchar(100) NOT NULL,
    model_title     varchar(100) NOT NULL,
    year_of_release int          NOT NULL,
    person_id       int          REFERENCES Person (id) ON DELETE SET NULL
);